<?xml version="1.0" encoding="UTF-8"?>
<!--this is an example of internal DTD-->
<!DOCTYPE family [
<!ELEMENT family (Num-Brothers, Name-of-brother, Num-of-kids, Name-of-kids)>
<!ELEMENT Num-Brothers (#PCDATA)>
<!ELEMENT Name-of-brother (#PCDATA)>
<!ELEMENT Num-of-kids (#PCDATA)>
<!ELEMENT Name-of-kids (#PCDATA)>
]>
<!--From here html code starts-->
<family>
<Num-Brothers> seven </Num-Brothers>
<Name-of-brother> Behader Shah, Muhammad Javeed, Haroon rasheed, Raja Akbar, Naveed Alam, Bahrooz Alam, Wajahat-uz-zaman </Name-of-brother>
<Num-of-kids> Four </Num-of-kids>
 <Name-of-kids> ikrash Alam, Arsh akbar, Azan akbar and sahil uz zamnan </Name-of-kids>
 </family>